name: "CI"

on:
  pull_request:
  push:

env:
  PHP_CURRENT: "8.4"
  PHP_NEXT: "8.5"

jobs:
  composer-json-lint:
    name: "Lint composer.json"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "pcov"
          php-version: "${{ env.PHP_CURRENT }}"
          ini-values: "${{ env.INI_VALUES }}"
          tools: composer-normalize, composer-require-checker
      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0

      - run: "composer validate --strict"
      - run: "composer-normalize --dry-run"

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "none"
          php-version: "${{ env.PHP_CURRENT }}"
          ini-values: "${{ env.INI_VALUES }}"
          tools: cs2pr
      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0

      - run: "vendor/bin/phpcs -q --report=checkstyle | cs2pr"

  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "none"
          php-version: "${{ env.PHP_CURRENT }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0

      - run: "vendor/bin/phpstan  --memory-limit=256M"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.4"
          - "8.5"
        dependencies:
          - "lowest"
          - "locked"
          - "highest"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run tests"
        timeout-minutes: 3
        run: "vendor/bin/phpunit --no-coverage --no-logging"

  code-coverage:
    name: "Code Coverage"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
      - uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2
        with:
          coverage: "pcov"
          php-version: "${{ env.PHP_CURRENT }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # 4.0.0

      - name: "Run Infection"
        timeout-minutes: 30
        run: "vendor/bin/infection --ansi --show-mutations --static-analysis-tool=phpstan"
        env:
          INFECTION_DASHBOARD_API_KEY: "${{ secrets.INFECTION_DASHBOARD_API_KEY }}"
          STRYKER_DASHBOARD_API_KEY: "${{ secrets.STRYKER_DASHBOARD_API_KEY }}"
